### PR TITLE
User following

### PR DESCRIPTION
**Pull request by JaiSharmaTech**

### CODE REVIEW

**Comment by JaiSharmaTech** [comment]
Added a route for following, and added prev checking so that the user cant follow someone twice

**Review by KartikeyKakaria — APPROVED** [review]
Nice, its good, i shall approve it. but i need to you to work on your naming conventions tho

**Comment by KartikeyKakaria** [comment]
thanks, i shall work on that as well

**Comment by JaiSharmaTech** [comment]
Thanks i shall work on that as well

**Pull request merged**
